# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4218d27fafd5691962e8e382a05ddf3aa6afa7f12a52b787d210345b79111a4a8fd84afc84287c0e310ee04bdbfdb29bcb7b464f5be574d10fc46779b8e70ca5

test:
  secret_key_base: 9034de7865a64312bd0cb3db2c963cbea2e0b98aa3603c92c35c2f3f05a717bea88c4e3c403b3b12920cb7ee880cceb2342f12e8e1ae09ffef79b53267684768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
